### ISSUE TITLE
Central sync publishing to JFrog OSS snapshots

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-project-template#22]
Maven Central sync seems to be broken in latest versions:

https://github.com/micronaut-projects/micronaut-test/runs/869533590?check_suite_focus=true#step:6:41

**Comment by alvarosanchez** [comment]
It must be related to the changes that were made to support micronaut-core. I will have a deeper look

**Comment by alvarosanchez** [comment]
Fixed in the plugin version 2.0.5. In the meantime, I have manually synced micronaut-test 1.2.1 in Central.

**Comment by graemerocher** [comment]
Thanks!
