### ISSUE TITLE
Merging a PR from a user always results in a failed changlog build

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-project-template#26]
If you merge a PR from a user a failed build occurs for the user always.

For example https://github.com/micronaut-projects/micronaut-gcp/runs/888906933?check_suite_focus=true

**Comment by alvarosanchez** [comment]
I don't understand why. We are using micronaut-build's `GH_TOKEN`:

https://github.com/micronaut-projects/micronaut-gcp/actions/runs/175386450/workflow#L57

**Comment by alvarosanchez** [comment]
This workflow is gone
