### ISSUE TITLE
SonarQube task fails for external PRs

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-project-template#261]
Hi, I have a couple of PRs in Micronaut AWS repository which are failing on SonarQube execution

see https://github.com/micronaut-projects/micronaut-aws/runs/8150663775?check_suite_focus=true#step:7:940

This makes the PR looking not ready even there are no static analysis issues found.

**Comment by musketyr** [comment]
But the missing token should be covered [here](https://github.com/micronaut-projects/micronaut-build/blob/master/src/main/java/io/micronaut/build/MicronautQualityChecksParticipantPlugin.java#L53). That's the reason why I have created the issue in https://github.com/micronaut-projects/micronaut-build. The internal plugin should disable the SonarQube task when the token is missing but it doesn't seem so.

**Comment by alvarosanchez** [comment]
That is working as expected. The problem is that the env variable is passed no matter what: https://github.com/micronaut-projects/micronaut-project-template/blob/master/.github/workflows/sonarqube.yml#L57

The whole workflow should not be run in that case.
