### ISSUE TITLE
Broken Link In Readme

### ISSUE THREAD

**Issue by jeffbrown** [micronaut-projects/micronaut-project-template#388]
### Issue description

In the current README is the following link:

`See the [Snapshot Documentation](https://micronaut-projects.github.io/micronaut-project-template/snapshot/guide/) for the current development docs.
`

https://micronaut-projects.github.io/micronaut-project-template/snapshot/guide/ is presently 404'ing.

I think the same is true for:

`See the [Documentation](https://micronaut-projects.github.io/micronaut-project-template/latest/guide/) for more information.`

**Comment by sdelamo** [comment]
This is template project. It is not meant to publish any documentation.
