### ISSUE TITLE
Create an action that publishes the test reports

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-project-template#6]
It should publish the HTML reports to a location in GitHub pages, and report the URL using the GitHub Checks API.

**Comment by ilopmar** [comment]
Another option could be enable the [build scan](https://guides.gradle.org/creating-build-scans/) so we can look for the url in the log and go there to have a detailed view of what happened.

**Comment by alvarosanchez** [comment]
Does that publish the HTML reports too? If so, that would be much better. Otherwise, we can do both

**Comment by ilopmar** [comment]
This is one I just published for liquibase: https://scans.gradle.com/s/u5prdufuiubzw

**Comment by alvarosanchez** [comment]
So it doesn't publish them. I wonder what would be the output with failed tests.

**Comment by ilopmar** [comment]
There you go: https://scans.gradle.com/s/e5rdme7laarny/tests/:flyway:test/io.micronaut.flyway.FlywayConfigurationPropertiesEnabledSpec/if%20no%20flyway%20configuration%20then%20no%20FlywayConfigurationProperties%20and%20Flyway%20beans%20are%20created#1

**Comment by alvarosanchez** [comment]
Great!

However, the goal of this issue was to avoid scrolling through the GitHub actions logs to see what test failed. Not sure if scrolling to see the scan URL is any better, though.

**Comment by ilopmar** [comment]
Yeah, kind of agree. In any case the build scan adds a lot of information that we may need in the future, so we probably do both things.

**Comment by graemerocher** [comment]
Apparently you can use Github Actions Annotations to show test failures. See https://github.community/t/what-are-annotations/16173/3

Example https://github.com/humio/test-annotations-action

**Comment by graemerocher** [comment]
May be useful as well https://github.com/shyim/junit-report-annotations-action

**Comment by graemerocher** [comment]
This one looks more complete https://github.com/marketplace/actions/surefire-report

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-project-template/commit/dcd6def9be5ffa645f5591fc9971ecbc5656b628

But needs an update to the gradle plugins to include:

```groovy
    project.tasks.withType(Test) {
        reports {
          junitXml.enabled = true
        }        
    }     
```

**Comment by alvarosanchez** [comment]
@graemerocher the action used doesn't seem to work in this case: https://github.com/micronaut-projects/micronaut-rabbitmq/runs/843396343

Do you know why?

**Comment by graemerocher** [comment]
@alvarosanchez looking at the logs, no test report was generated.. something is wrong with the build that causes a NPE at the runner level

**Comment by alvarosanchez** [comment]
I restarted the jobs and they passed now.

🤷‍♂️

**Comment by alvarosanchez** [comment]
Closing this as the current solution seems sufficient.
